### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by oliver8459** [lschmidtke/shape_templates#1]
could u please upload pretrained model? thx!

**Comment by lschmidtke** [comment]
Hi! I'm a bit busy at the moment due to the next paper deadline, but I'll try to train and upload this week!

**Comment by lschmidtke** [comment]
Hi,

training with the rewritten code proved a bit unstable, I'm trying some improvements now. Sorry for the delay, please stay tuned!

**Comment by oliver8459** [comment]
It's ok. Thanks very much!

**Comment by lschmidtke** [comment]
Hi, I uploaded the pretrained model, check out src/core/pretrained_model.py for details.
