### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by MehwishG** [lschmidtke/shape_templates#4]
I read your paper it seems very interesting for Human Pose Estimation in unsupervised manner. It would be great if you can share the Pre-trained Model for Human 3.6M dataset.

**Comment by lschmidtke** [comment]
Hi,

I'm working on it currently! There was a problem with my data sampling.

**Comment by MehwishG** [comment]
Thanks for the update.

**Comment by MehwishG** [comment]
Thanks
