### ISSUE TITLE
How to create a template and anchor points?

### ISSUE THREAD

**Issue by aoikaneko** [lschmidtke/shape_templates#5]
Hi, thanks for the great work. I have a question regarding template.json and anchor_points.json.
How center points and variances (template.json) and anchor point coordinates (anchor_points.json) are obtained? Also, how did you define the number of anchor points for each body part?

**Comment by lschmidtke** [comment]
Hi,

the parameters in the json were defined by hand. We simply selected the ones that resembled a reasonable, average human body. The anchor points resemble the joints that are used in pose estimation papers we compare to, but you can define them differently. Ie. you could model the shoulder as one part connected to the core, with three anchor points: one in the middle and two on each side connecting to arms.

Hope that answers your question!

**Comment by aoikaneko** [comment]
Thank you for your helpful answer!
